// this code is generated by chatGPT
// plain linked list implementation

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define RANDOM_NUMBERS 100000

typedef struct Node {
    char name[50];
    int income;
    struct Node* next;
} Node;

Node* head = NULL;

void insert(char name[], int income) {
    Node* new_node = (Node*)malloc(sizeof(Node));
    strcpy(new_node->name, name);
    new_node->income = income;
    new_node->next = NULL;
    
    if (head == NULL) {
        head = new_node;
        return;
    }
    
    Node* curr = head;
    Node* prev = NULL;
    while (curr != NULL && curr->income < income) {
        prev = curr;
        curr = curr->next;
    }
    
    if (prev == NULL) {
        new_node->next = head;
        head = new_node;
    } else {
        prev->next = new_node;
        new_node->next = curr;
    }
}

//void delete(char* name) {
//    Node* temp = head, *prev = NULL;
//    
//    while (temp != NULL && strcmp(temp->name, name) != 0) {
//        prev = temp;
//        temp = temp->next;
//   }
//
//    if (temp != NULL) {
//        if (prev == NULL) {
//            head = temp->next;
//        } else {
//            prev->next = temp->next;
//        }
//        free(temp);
//    }
//}

void range_search(int value, int flag) {
    Node* curr = head;
    while (curr != NULL) {
        if (flag == 0 && curr->income < value) {
            // printing will take a long time
            //printf("%d\n", curr->income);
        } else if (flag == 1 && curr->income >= value) {
            //printf("%d\n", curr->income);
        } else if (flag == 0 && curr->income >= value) {
            break;  // since the values are always sorted, when a value is greater than or equal, we can stop
        }
        curr = curr->next;
    }
}

void range_search2(int start, int end) {
    Node* curr = head;
    while (curr != NULL) {
        if (curr->income >= start && curr->income < end) {
            //printf("%d\n", curr->income);
        } else if (curr->income >= end) break;
        curr = curr->next;
    }
}

int main() {
    struct timespec begin, end;

    // generate random numbers
    int lower = 0, upper = 500000;
    srand(time(0));  // random seed

    printf("Insert 100000 records...\n");
    clock_gettime(CLOCK_MONOTONIC_RAW, &begin);
    for (int i=0; i<RANDOM_NUMBERS; i++) {
        insert("_", (rand() % (upper - lower + 1)) + lower);
    }
    clock_gettime(CLOCK_MONOTONIC_RAW, &end);
    printf("Total time = %f seconds\n\n", (end.tv_nsec - begin.tv_nsec)/1000000000.0 + (end.tv_sec - begin.tv_sec));
    
    printf("People with less than 50,000\n");
    clock_gettime(CLOCK_MONOTONIC_RAW, &begin);
    range_search(500000, 0); // search for all names with income less than 50000
    clock_gettime(CLOCK_MONOTONIC_RAW, &end);
    printf("Total time = %f seconds\n\n", (end.tv_nsec - begin.tv_nsec)/1000000000.0 + (end.tv_sec - begin.tv_sec));

    printf("People with income between 1000 and 80000.\n");
    clock_gettime(CLOCK_MONOTONIC_RAW, &begin);
    range_search2(1000, 80000);
    clock_gettime(CLOCK_MONOTONIC_RAW, &end);
    printf("Total time = %f seconds\n\n", (end.tv_nsec - begin.tv_nsec)/1000000000.0 + (end.tv_sec - begin.tv_sec));

    //printf("People with more than 50,000\n");
    //range_search(50000, 1); // search for all names with income greater than or equal to 50000
    //printf("\n");

    //printf("Delete Yara.\n");
    //clock_gettime(CLOCK_MONOTONIC_RAW, &begin);
    //delete("Yara");
    //clock_gettime(CLOCK_MONOTONIC_RAW, &end);
    //printf("Total time = %f seconds\n\n", (end.tv_nsec - begin.tv_nsec)/1000000000.0 + (end.tv_sec - begin.tv_sec));

    return 0;
}
